dist: xenial
language: node_js

node_js:
  - 12

addons:
  chrome: stable
  firefox: latest-nightly

env:
  - BROWSER_NAME=chrome
  - BROWSER_NAME=firefox

script:
  - npm run test:headless -- --${BROWSER_NAME}
